--Every command here will be executed when the container is created

CREATE TABLE IF NOT EXISTS mytable (
    MYID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS mytable2 (
    MYID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

INSERT INTO mytable (DESCRIPTION) VALUES ('TESTE');
INSERT INTO mytable (DESCRIPTION) VALUES ('TESTE2');

CREATE TABLE CATEGORIES (
    CODE  SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    TAX NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
    CODE SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE NUMERIC(10,2),
    AMOUNT NUMERIC(10) NOT NULL,
    CATEGORY_CODE INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE) ON DELETE CASCADE,
    CONSTRAINT chk_negative CHECK (amount >= 0)
);

CREATE TABLE CART(
    CODE SERIAL PRIMARY KEY,
    PROD INTEGER,
    PRICE NUMERIC(10, 2),
    AMOUNT NUMERIC(10),
    TOTAL NUMERIC(10),
    TAX NUMERIC(10, 2),
    CONSTRAINT FK_PROD FOREIGN KEY (PROD) REFERENCES PRODUCTS(CODE)
);

CREATE TABLE ORDERS (
    CODE SERIAL PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2)
);

CREATE TABLE ORDER_ITEM(
    CODE SERIAL PRIMARY KEY,
    ORDER_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES ORDERS(CODE)
);

CREATE TABLE USERS(
    CODE SERIAL PRIMARY KEY,
    USERNAME VARCHAR(125),
    EMAIL VARCHAR(125),
    PWD VARCHAR(125)
);